### PR TITLE
Fixes #2, #3, #6, & #7 -- UCIT theme tweaks

### LINKED ISSUE #2: Make "Featured Item" thumbnail smaller
**Issue:**

- At the current size, the image quality is poor.
- Can the size be constrained so it doesn't get too big and lead to grainy images? Responsive design issue?

See:
https://library.ucsd.edu/tellushowucit/

Example:
image2017-2-2 18-27-15

### LINKED ISSUE #3: Update footer to include Library logo, etc.
**Issue:**

- The footer should have the Library's contact info, logo, and link back to the Library home page.
- Change from this:

image2017-2-2 18-27-15
- To something more like this:

image2017-2-2 18-29-27

- See:
    - https://library.ucsd.edu/tellushowucit/

### LINKED ISSUE #6: Sorting by Creator does not display the results
**Issue:**

- When you sort by Creator, creator(s) doesn't actually display in the results.
- Investigate how to make them display in the UI results.

image2017-2-2 18-36-22

### LINKED ISSUE #7: Investigate lifting character limit on collection description
**Issue:**

- Look to see if there is a way to increase the character limit on the collection description.

image2017-2-2 18-36-22

### PR DESCRIPTION
**Pull request by dt-ucsd**
[Fixes #3 - Update theme footer]
Added Library logo to footer. Placed it on the right side. Left side
container can still take custom HTML via theme interface control.

[Fixes #2 - Featured item thumbnail]
Added a max-width property (200px) to the featured image. It matches
the resolution the thumbnails are set to on the site. Also added styles
to ensure image is centered within its container. Changes affect
desktop view only.

[Fixes #6 - Display Creator metadata in Description container]
Added Creator metadata to Description container on “items” browse view.
Doesn’t display if Creator is an empty string.

[Fixes #7 - Increase character limits of browse descriptions]
Increased character limit of browse views item descriptions to 1000
(items & collections).

### CODE REVIEW

**Comment by mcritchlow** [comment]
LGTM 👍 

Will merge once @gamontoya has a chance to review the screenshots, barring any change requests.

**Comment by gamontoya** [comment]
@mcritchlow Matt, the screenshots look good.

**Comment by mcritchlow** [comment]
@gamontoya great, thanks! Merge coming @dt-ucsd

**Comment by gamontoya** [comment]
@mcritchlow @dt-ucsd What's left here to push these changes to production?

**Comment by mcritchlow** [comment]
@gamontoya - may need to ask @jhriv to deploy the theme changes.

John, can you do that at your earliest convenience please?

**Comment by gamontoya** [comment]
@jhriv Can you deploy today or would you rather deploy during your morning service window?

**Comment by jhriv** [comment]
I can do it today. It's still a very manual process, though.

**Pull request merged**
